CREATE TABLE IF NOT EXISTS produto_imagens (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    codi_psv VARCHAR(20) NOT NULL,
    url_imagem TEXT NOT NULL,
    data_cadastro DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (codi_psv) REFERENCES PRODSERV(CODI_PSV)
); 